# Expresiones regulares...
# Los teléfonos de EEUU son del tipo: 415-555-4242
# Los podríamos detectar muy fácilmente con esta expresión regular (regex)
# \d\d\d-\d\d\d-\d\d\d\d          \d significa un dígito....
# un número entre llaves indica repetición de la expresión anterior...
# Por ejemplo, los números de teléfono los podríamos escribir
# con la regex simplificada...   \d{3}-\d{3}-d{4}

# Python incluye el módulo re
# Luego debemos usar la función re.compile , utilizando como argumento una r-string
# para crear un Pattern(Regex) object que es lo que usaremos...
# Por ejemplo, para reconocer los números EEUU haríamos...
import re
phone_number_regex_object = re.compile(r'\d\d\d-\d\d\d-\d\d\d\d')
# También por supuesto serviría con re.compile(r'\d{3}-\d{3}-d{4}')

# Ahora ya podemos usar el Pattern / Regex object con el método search() para
# buscar el patrón en el texto que le pasemos...
# la función search() devuelve un match_object con las coincidencias...
# si no hay coincidencia, devolvería None
message = 'Call me at 415-555-111 tomorrow. 415-555-9999 is my office.'
match_object = phone_number_regex_object.search(message)
# si hay coincidencia...
if match_object:
    print('Phone number found: ' + match_object.group())
